# Generated by Django 3.0 on 2024-03-23 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Busnumber', models.CharField(default='', max_length=10)),
                ('Registrationnumber', models.CharField(max_length=20)),
                ('Model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Housename', models.CharField(default='', max_length=20)),
                ('Place', models.CharField(default='', max_length=20)),
                ('Post', models.CharField(default='', max_length=20)),
                ('Pin', models.CharField(default='', max_length=6)),
                ('Phonenumber', models.CharField(default='', max_length=15)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Experience', models.CharField(default='', max_length=10)),
                ('Photo', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('Type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Class', models.CharField(default='', max_length=10)),
                ('Housename', models.CharField(default='', max_length=20)),
                ('Division', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('Place', models.CharField(default='', max_length=20)),
                ('Post', models.CharField(default='', max_length=20)),
                ('Pin', models.CharField(default='', max_length=6)),
                ('Guardianname', models.CharField(default='', max_length=20)),
                ('Phonenumber', models.CharField(default='', max_length=10)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Photo', models.CharField(default='', max_length=100)),
                ('Rfidnumber', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_place', models.CharField(max_length=20)),
                ('To_place', models.CharField(max_length=20)),
                ('Amount', models.CharField(max_length=1000)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Parentmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Bus')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Latitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Feepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Month', models.CharField(max_length=25)),
                ('Duedate', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Facedetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('Photo', models.CharField(default='', max_length=500)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Drivermessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Bus')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='LOGIN',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Login'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=500)),
                ('Reply', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Student')),
            ],
        ),
        migrations.CreateModel(
            name='checkincheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=500)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Busrelatedmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='Driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Driver'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Bus')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safetrack.Student')),
            ],
        ),
    ]
